# Generated by Django 3.2 on 2024-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remeras',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Unisex')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='remeras',
            name='talle',
            field=models.IntegerField(choices=[(1, ' Extra Small'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Extra Large'), (6, 'Super Extra Large')], default=1, null=True),
        ),
    ]
